### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by H5820121** [adirh3/Fluent-Search#1108]
1. When you resize the right/left side of the search window (without changing the overall size of the window), FS does not remember the size of the right/left side even though the Remember Window Size setting is enabled. And every time FS is restarted, for example after installing a Windows update that requires a restart, the right/left side size must be resized.
 I also tried it on another computer with a "clean install" of FS, and the same problem.
In which json file should this information be saved and where in the file is it located? Maybe I should try to manually change this information?
2. The keyboard shortcut in Tooltip needs an update: 

![Image](https://github.com/user-attachments/assets/142006e1-66e8-4145-9568-00a2733f99db)

4. By the way, how can I change the location of the index DB file? I need it to be on a different drive than C?
Thanks!

**Comment by adirh3** [comment]
Thanks for the feedback!
Only way to currently move the index location is by using the portable version (it will be next to EXE)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.77. Changelog - https://github.com/adirh3/Fluent-Search/releases/tag/1.0.0.77

**Comment by ligq** [comment]
> This issue has been potentially fixed in version 1.0.0.77. Changelog - https://github.com/adirh3/Fluent-Search/releases/tag/1.0.0.77

The new version still cannot remember the window size.
I am using the latest version of FS (1.0.0.77) and windows 24H2 (26100.2894)

**Comment by H5820121** [comment]
@adirh3
Unfortunately, this issue is still not solved!

‫בתאריך יום ג׳, 21 בינו׳ 2025 ב-10:46 מאת ‪Lighto‬‏ <‪
***@***.***‬‏>:‬

**Comment by H5820121** [comment]
@adirh3 
> This issue has been potentially fixed in version 1.0.0.77. Changelog - https://github.com/adirh3/Fluent-Search/releases/tag/1.0.0.77

Unfortunately, this issue is still not solved!

**Comment by H5820121** [comment]
@adirh3
If you reduce the width of the side where the file list is displayed (right
side in RTL), it does remember. But when you increase the width of that
side (which is what is needed more), it does not remember.

‫בתאריך יום ג׳, 21 בינו׳ 2025 ב-10:46 מאת ‪Lighto‬‏ <‪
***@***.***‬‏>:‬
