### ISSUE TITLE
Can't click the menu in screen search

### ISSUE THREAD

**Issue by ZHLONG-CN** [adirh3/Fluent-Search#1148]
**Describe the bug**
I can't use screen search to click the right lick menu. Because the "Fluent Search - Screen Search" window will focus after I press the screen search hotkey, and the menu will close.

I am not an Avalonia developer, but there are `WS_EX_NOACTIVATE` and `WS_EX_NOACTIVATE` flags in winapi to create a window without focus.

By the way, I search avalonia and got the way to implement.
https://github.com/AvaloniaUI/Avalonia/discussions/15805

Also, the taskbar icon is optional, it shuold be hidden, because the screen search window is no a "Window".

**To Reproduce**
Right click anywhere, and use screen search hotkey. The meun will close.

**Expected behavior**
Right click anywhere, and use screen search hotkey, click the menu item.

**Screenshots**
No.

**Desktop (please complete the following information):**
 - Window 10/11 Version: pro 22h2
 - Fluent Search Version: 0.9.92.998
 - Installation source: Installer

**Additional context**
The screen search window infomation:
```
ClassName: Avalonia-fb532459-d6c8-42c1-8c53-8d4bf611c075
WinidowText: Fluent Search - Screen Search
```

**Comment by adirh3** [comment]
@ZHLONG-CN can you please update to 1.0.0? or download from here https://fluentsearch.net
I fixed this issue in this release

**Comment by ZHLONG-CN** [comment]
> [@ZHLONG-CN](https://github.com/ZHLONG-CN) can you please update to 1.0.0? or download from here https://fluentsearch.net I fixed this issue in this release

Still cannot click the menu because the window lose focus.
Fluent Search Version: 1.0.0.95

How to reproduce:
1. open the chrome browser
2. use hotkey to open screen search
3. click the "three dots" on the top right corner, and the menu will show
4. use hotkey to open screen search again
5. chrome will lose focus, and the menu will close at the same time

**Comment by NateMarrocco** [comment]
I have the same problem in steam, and Id imagine all popup menus, including right clicking the windows decktop. With steam if you click the steam menu in the top left, or in firefox if you click the three horizontal lines--a pop up menu opens, I hit ctrl-m, hints for the pop up menu appear, but then in the process of typing ctrl-m the pop up dispersal with the hints for the popup remaining.
