### ISSUE TITLE
System tray right click menu rendering incomplete on irregular monitor resolutions

### ISSUE THREAD

**Issue by Kamaris521** [adirh3/Fluent-Search#1209]
Using a stacked monitor configuration, where the top monitor has a high resolution than the bottom one, and the system tray is on the top monitor's lower right corner. When right clicking the system tray icon to bring up the menu, it is cutting off items from the menu.

<img width="454" height="370" alt="Image" src="https://github.com/user-attachments/assets/24be58a4-53f8-44b9-947b-7eea71be3ac4" />

<img width="341" height="167" alt="Image" src="https://github.com/user-attachments/assets/faf6aaec-beb4-4181-9e01-2b5a12ebc718" />

 - Window 10 22H2
 - Fluent Search Version: 1.0.0.85, 1.0.1.2, 1.0.1.4, 1.0.1.4 nightly
 - Installation source: Installer

**Comment by adirh3** [comment]
@Kamaris521 can you please try with version 1.1.0.x? You can download from here  - https://github.com/adirh3/Fluent-Search/releases

I can't reproduce this problem with similar setup - 31:9 + 16:9 monitors. Can you please share your screen resolutions and DPIs?

**Comment by Kamaris521** [comment]
<img width="716" height="383" alt="Image" src="https://github.com/user-attachments/assets/01919157-aaeb-4409-96b1-869b6884fa02" />

Same cutoff.

5120x1440 (top monitor)
3440x1440 (bottom monitor)
Windows DPI Scaling is 100% for both monitors.

**Comment by adirh3** [comment]
@Kamaris521 do you use any Windows taskbar customization software?

**Comment by Kamaris521** [comment]
The only thing I have installed that might fall into that category is DisplayFusion Pro. I believe it has some Taskbar features but I don't have them enabled, as I use the software for placement of application windows across both monitors. I did exit it and relaunch Fluent to retest, and the behavior is the same.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.1.0.10. Changelog - https://github.com/adirh3/Fluent-Search/releases/tag/1.1.0.10

**Comment by Kamaris521** [comment]
Issue persists. Works if top monitor is set to main display, but cuts off screen when not main display.
