### ISSUE TITLE
Webviews Bug

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#1214]
![Image](https://github.com/user-attachments/assets/f333ab5d-dfc2-4a1a-930d-2e17ac7ffce6)

preview is out of bounds. [notice right side panel]
the web page appears outside the window bounds

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.1.0.6. Changelog - https://github.com/adirh3/Fluent-Search/releases/tag/1.1.0.6

**Comment by mragtronx8** [comment]
> This issue has been potentially fixed in version 1.1.0.6. Changelog - https://github.com/adirh3/Fluent-Search/releases/tag/1.1.0.6

@adirh3 issue still persists [v1.1.0.6 04Oct2025]

<img width="827" height="632" alt="Image" src="https://github.com/user-attachments/assets/34307c36-1cef-449d-815b-23c378e41d75" />

**Comment by adirh3** [comment]
@mragtronx8 which version of Windows are you using?

**Comment by mragtronx8** [comment]
> [@mragtronx8](https://github.com/mragtronx8) which version of Windows are you using?

windows 10 22h2

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.1.0.9. Changelog - https://github.com/adirh3/Fluent-Search/releases/tag/1.1.0.9
