### ISSUE TITLE
Problems with Chinese search！

### ISSUE THREAD

**Issue by RainyGrass** [adirh3/Fluent-Search#1231]
<img width="1200" height="737" alt="Image" src="https://github.com/user-attachments/assets/0f1f0c66-ee77-43a2-bb6c-4e90a5ce864d" />

As this scenario illustrates, when I search for files named "第一组" it returns several results, of which the one I circled is the correct file! However, the results only display "第一"? The rest of the text doesn't appear. This is strange because the filename on my desktop is indeed "第一组.pdf". I tried expanding the interface, but clearly, the full name isn't showing up.

<img width="108" height="122" alt="Image" src="https://github.com/user-attachments/assets/cb737c87-6241-4e0e-998c-1a9040144c97" />

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.1.1.2. Changelog - https://github.com/adirh3/Fluent-Search/releases/tag/1.1.1.2

**Comment by RainyGrass** [comment]
The problem persists: the image of the red and blue sphere is named "测试图" but the search results only show the one word "测"

**Comment by RainyGrass** [comment]
<img width="1200" height="737" alt="Image" src="https://github.com/user-attachments/assets/2f25cb22-fa83-4c71-b45d-839d4aca6a31" />

**Comment by RainyGrass** [comment]
It's actually not a big deal, it's just a bit annoying to look at. If you don't have this problem when you test it, then I won't pay any more attention to this error :)
