### ISSUE TITLE
"Map searched tag" isn't working

### ISSUE THREAD

**Issue by Nomad-0** [adirh3/Fluent-Search#131]
**Describe the bug**
The tags I mapped in _map searched tag_ aren't working anymore. 

**To Reproduce**
1. map a tag with 1 or 2 character
2. invoke fs and type the character

**Expected behavior**
If I type the input the tag I mapped should appear in suggestions+the tag in the output should be enabled when I press `tab`

**Screenshots**
these are the tags I mapped
![image](https://user-images.githubusercontent.com/76395594/122405667-0d511000-cfa2-11eb-9bc1-43df1ec2fad9.png)

If I press `a` -> `tab`, the tag here should be apps

![image](https://user-images.githubusercontent.com/76395594/122405750-1f32b300-cfa2-11eb-9c79-1c0f2b9fcece.png)

If I type `bk`, the suggestions should show bookmarks only. If I press `tab` here, it searches the _chromium_ instead of _bookmarks_

![image](https://user-images.githubusercontent.com/76395594/122405794-28bc1b00-cfa2-11eb-904a-3b7819c04b28.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: [21H2]
 - Fluent Search Version [0.9.85.65]

**Additional context**
It was working all right in previous versions

**Comment by Metroid-Prime** [comment]
@Metroid-Prime  tagging myself as I need to track this one.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.70

**Comment by Metroid-Prime** [comment]
@Nomad-0  can you verify?

**Comment by Nomad-0** [comment]
Still not working for some tags

![image](https://user-images.githubusercontent.com/76395594/122506506-4a5be780-d020-11eb-83dc-9c217d7aa9f7.png)

**Comment by adirh3** [comment]
@Nomad-0 there is no tab called "bookmarks" it's "bookmark", this issue is fixed.
Note you can use little lightbulb at the top right to insert valid tags

**Comment by Nomad-0** [comment]
got it, thank you
