### ISSUE TITLE
Increase start menu drag and drop area 

### ISSUE THREAD

**Issue by Mr-Frankenstein** [adirh3/Fluent-Search#183]
In the start menu, I can only drag and drop results on top of other pinned results.
(From **recent** to **pinned**)

https://user-images.githubusercontent.com/85425543/123739108-bad9f280-d8c3-11eb-97ea-e44b7186b817.mp4

I should be able to drag and drop on the right side of the pinned results.

**Comment by adirh3** [comment]
@Mr-Frankenstein Should be fixed, please close after you confirm

**Comment by Mr-Frankenstein** [comment]
This is still not fixed for me :(
Drag & Drop seems to be working sometimes fine and sometimes not.

Uploading 2021-07-16_12-07-19.mp4…

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.85

**Comment by Mr-Frankenstein** [comment]
> This issue has been potentially fixed in version 0.9.88.85

It is fixed and working perfectly now :). Thx.
