### ISSUE TITLE
Settings resizing error when maximizing

### ISSUE THREAD

**Issue by Mr-Frankenstein** [adirh3/Fluent-Search#206]
**Describe the bug**
When FS settings is maximized, all the settings don't resize.

**To Reproduce**
1. Open FS settings
2. Click on the maximize icon
3. See error

**Expected behavior**
All the settings should resize.

**Screenshots**
![image](https://user-images.githubusercontent.com/85425543/124504266-bdb57580-dde4-11eb-87b5-0aca49c3f373.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1
 - Fluent Search Version: 0.9.88.4

**Additional context**
All settings resized fine before the maximizing and minimizing feature is implemented.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.65

**Comment by Mr-Frankenstein** [comment]
It is still not fixed for me

![image](https://user-images.githubusercontent.com/85425543/125903057-4ab38202-0373-4bc3-81f1-ddb2a53ecd80.png)

**Comment by Metroid-Prime** [comment]
Confirming @Mr-Frankenstein  's report. I'm still seeing this too.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.88.97
