### ISSUE TITLE
Can't Copy Files

### ISSUE THREAD

**Issue by Chance92** [adirh3/Fluent-Search#316]
**Describe the bug**
Can't copy files in FS either with hot keys or mouse click.

**To Reproduce**
1. Set a key gesture for copying file;
2. Invoke FS and search for a file;
3. Use key gesture to copy the file or click the "Copy file" option in the right menu;
4. Try to paste it somewhere.

**Expected behavior**
It should work as intended.

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1
 - Fluent Search Version 0.9.89.9931

**Comment by adirh3** [comment]
Thanks @Chance92, how bad would it be if this won't be part of 0.9.89. stable?
Currently this single feature will add 90MB to installation folder until I figure out something lol

**Comment by Chance92** [comment]
So it is removed intentionally? I thought there's something wrong with my pc, because no one else seems to mention it. I have 297GB free in my C drive so I don't care about an extra 90MB :sunglasses: That being said, I can understand the concern and I can live without it until you figure it out. BTW can this function be made into a plugin?

**Comment by adirh3** [comment]
> So it is removed intentionally? I thought there's something wrong with my pc, because no one else seems to mention it. I have 297GB free in my C drive so I don't care about an extra 90MB 😎 That being said, I can understand the concern and I can live without it until you figure it out. BTW can this function be made into a plugin?

Technically yes it can be made into plugin, but I just can't bring myself to create a 90MB plugin lol
Hopefully I might be able to fix it soon :)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.93

**Comment by Chance92** [comment]
@adirh3 Thanks for the update. However, it seems the copy function can only work for once. I copied a file, it worked, but when I tried to copy and paste another file, I still get the first file.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.94

**Comment by Chance92** [comment]
Seems to work fine now. Thanks.
