### ISSUE TITLE
Duplicated/Irrelevant Result Groups

### ISSUE THREAD

**Issue by Chance92** [adirh3/Fluent-Search#335]
**Describe the bug**
Some search terms will let FS to show irrelevant result groups.

**To Reproduce**
1. Search for something;
2. See error

**Expected behavior**
Not to show irrelevant results.

**Screenshots**
![image](https://user-images.githubusercontent.com/85488695/137719472-d4a11c73-e359-4b87-89cf-181f5862edfa.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H1
 - Fluent Search Version 0.9.89.9965

**Additional context**
Group settings:
![image](https://user-images.githubusercontent.com/85488695/137719502-b9d4bae7-847e-4b42-83a1-c106fa3ade1c.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.0

**Comment by Chance92** [comment]
@adirh3 It appears to be fixed at the beginning. Once I rebuild the index the bug returned. It seems to happen more randomly now.
![image](https://user-images.githubusercontent.com/85488695/139560918-f91dc908-9052-4003-a4e3-6e1a20036919.png)

**Comment by Chance92** [comment]
Looks like the calculator can duplicate as well.
![image](https://user-images.githubusercontent.com/85488695/139561297-49707941-1137-4dec-b407-f0353ce9a248.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.1

**Comment by Chance92** [comment]
The calculator seems to be fixed, but the irrelevant groups still show up sometimes.
![image](https://user-images.githubusercontent.com/85488695/139580345-7a7d59f0-c6ad-4838-b643-6553d0bf163e.png)
![image](https://user-images.githubusercontent.com/85488695/139580347-b98165a4-60d7-459d-830c-ca4db78afff1.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.15

**Comment by Chance92** [comment]
> This issue has been potentially fixed in version 0.9.90.15

Unfortunately it is still there. Shall I try a clean install?

**Comment by adirh3** [comment]
> > This issue has been potentially fixed in version 0.9.90.15
> 
> Unfortunately it is still there. Shall I try a clean install?

No, can you re-explain the exact issue please.

**Comment by Chance92** [comment]
> > > This issue has been potentially fixed in version 0.9.90.15
> > 
> > 
> > Unfortunately it is still there. Shall I try a clean install?
> 
> No, can you re-explain the exact issue please.

Here's an example:
![bug](https://user-images.githubusercontent.com/85488695/140968218-820c3e75-47cd-4496-9c65-b57fd063863c.gif)
Here's another:
![bug1](https://user-images.githubusercontent.com/85488695/140969834-712ef17f-59c0-4f64-ad5e-0c2418428b44.gif)

**Comment by adirh3** [comment]
> > > > This issue has been potentially fixed in version 0.9.90.15
> > > 
> > > 
> > > Unfortunately it is still there. Shall I try a clean install?
> > 
> > 
> > No, can you re-explain the exact issue please.
> 
> Here's an example: ![bug](https://user-images.githubusercontent.com/85488695/140968218-820c3e75-47cd-4496-9c65-b57fd063863c.gif) Here's another: ![bug1](https://user-images.githubusercontent.com/85488695/140969834-712ef17f-59c0-4f64-ad5e-0c2418428b44.gif)

Thank you, it's as I thought, but can't repro it anymore after 90.15, but will find it eventually

**Comment by adirh3** [comment]
@Chance92 can you please confirm you're on the latest nightly version?
If you are, can you please send me your settings files in PM in Discord? It's int `%appdata%\Blast\Settings`

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.87

**Comment by Chance92** [comment]
@adirh3 It is finally gone! Thanks! Let's hope it won't come back again.
