### ISSUE TITLE
Duplicated Results

### ISSUE THREAD

**Issue by IgnusG** [adirh3/Fluent-Search#338]
**Describe the bug**
Seems like lately all results have been duplicated - App search, Process search. File search is not influenced.

**To Reproduce**
It occurs while searching but I'm unsure if it's a setting or something else. All the items have the exact same paths too. If they are groups then the items in the groups are the same as well - like powerpoint in the screenshot below.

**Expected behavior**
Only one result per App, Process is shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/6438760/138089092-4914a12f-f269-4c82-be95-753d0df73a5d.png)

![image](https://user-images.githubusercontent.com/6438760/138089221-cad5a736-5020-410d-97e4-3ad0eae9e24e.png)

**Desktop (please complete the following information):**
 - Windows 10 Version:  21H2 OS build	22000.282
 - Fluent Search Version 0.9.89.9990

**Additional context**
I think it's unrelated to https://github.com/adirh3/Fluent-Search/issues/335 since that one deals with file search

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.0

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.1

**Comment by IgnusG** [comment]
This seems to still be an issue in 0.9.90.20 except it takes about a second for the second set of results to appear.
So initially the original ones are shown and then duplicates animate below each entry.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.25

**Comment by adirh3** [comment]
@IgnusG closing, feel free to reopen if it still happens

**Comment by IgnusG** [comment]
This is still an issue on 0.9.90.75

![image](https://user-images.githubusercontent.com/6438760/147276432-dd4b0b4e-4852-4e04-9702-c96e49286b05.png)

**Comment by IgnusG** [comment]
@adirh3 I cannot seem to reopen this issue anymore - perhaps it's been locked or something similar

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.87

**Comment by IgnusG** [comment]
This seems to be fixed as of version 0.9.90.92
