### ISSUE TITLE
Unpin is hidden when there are to many items.

### ISSUE THREAD

**Issue by AnderssonPeter** [adirh3/Fluent-Search#348]
**Describe the bug**

**To Reproduce**
1. Go to 'Home screen'
2. Right click on 'Item' with many alternatives
3. The unpin option is outside the screen

**Expected behavior**
The unpin option should always be available

**Screenshots**
![image](https://user-images.githubusercontent.com/1308309/139387843-c9853189-906f-4d5b-a187-b08fdd362914.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: [e.g. 20H2]
 - Fluent Search Version [e.g. 0.9.89.9990]

**Comment by adirh3** [comment]
Thanks @AnderssonPeter, should be fixed (using scrollbar) on the latest nightly if you'd like to verify

**Comment by AnderssonPeter** [comment]
Hi @adirh3 sadly the issue does still exists (what about moving it to under uninstall app?)
![image](https://user-images.githubusercontent.com/1308309/141426988-2afdc721-553e-4894-98dc-19bf39000e59.png)


Also the settings icon in the launcher is gone (can still find it in the tray icon, don't know if its a bug)

Also the text to speech the first time you start the app is annoying as hell.

**Comment by adirh3** [comment]
> Hi @adirh3 sadly the issue does still exists (what about moving it to under uninstall app?) ![image](https://user-images.githubusercontent.com/1308309/141426988-2afdc721-553e-4894-98dc-19bf39000e59.png)
> 
> Also the settings icon in the launcher is gone (can still find it in the tray icon, don't know if its a bug)
> 
> Also the text to speech the first time you start the app is scary (i jump like a meter every time) and annoying as hell.

Setting icon change is intended.
You get text to speech every time you start the app? It should show start only on the welcome window

**Comment by AnderssonPeter** [comment]
I only get it the first time, but as i downloaded the nightly portable version i got it again, it's no biggie just unusual for a app to start talking when you start it, normally that's something you enable not the other way around.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.25

**Comment by adirh3** [comment]
@AnderssonPeter closing, I can't repro it anymore, if it still happens for you please reopen the issue.

**Comment by AnderssonPeter** [comment]
Is your fix in the stable release?

**Comment by adirh3** [comment]
> Is your fix in the stable release?

This issue could happen because of two bugs, one was fixed in stable, and one (you mentioned) is fixed in nightly 0.9.90.25.
