### ISSUE TITLE
Right Side Bar Appearance

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#364]
Right Side Bar Icons/Words are not displaying correctly
#BUG

![image](https://user-images.githubusercontent.com/62798102/141650439-17cfae4b-129e-4996-b1a6-8af42b3ab5ba.png)
![image](https://user-images.githubusercontent.com/62798102/141650362-b6138fce-92a0-4474-9d2f-13bfd49cb5bf.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.45

**Comment by mragtronx8** [comment]
> This issue has been potentially fixed in version 0.9.90.45

issue not solved, it is still in v0.9.90.45
![image](https://user-images.githubusercontent.com/62798102/143684417-2e014b96-3b9d-4503-9b69-3bdf98313806.png)
![image](https://user-images.githubusercontent.com/62798102/143684458-48181bee-6a6d-4885-91f2-3c91fb44f7d1.png)
![image](https://user-images.githubusercontent.com/62798102/143684469-0dc3b427-ee96-4fe1-997b-a4b4232069ed.png)
