### ISSUE TITLE
Always hide results when opening is not working

### ISSUE THREAD

**Issue by Nomad-0** [adirh3/Fluent-Search#37]
**the bug**
 I have `Always hide results when opening` enabled on settings. But pressing on hotkey still keep showing previous search results

**To Reproduce**
make a search. close FS. Reopen FS with the hotkey.

**Expected behavior**
Only the Search-bar to appear like this
![image](https://user-images.githubusercontent.com/76395594/120911428-4a1b2e00-c6a9-11eb-846e-0d1f78d2e5b8.png)

**Screenshots**
this is what I see
![image](https://user-images.githubusercontent.com/76395594/120911446-5c956780-c6a9-11eb-93e8-71a6af38921b.png)

even if I restart FS, I see this on the first search
![image](https://user-images.githubusercontent.com/76395594/120911559-260c1c80-c6aa-11eb-882b-b659c94f7a2d.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: [21h1]
 - Fluent Search Version [0.9.85.1]

**Comment by mochigithub** [comment]
Can confirm. This is a high priority bug.
![image](https://user-images.githubusercontent.com/1836362/120915233-8c1b8400-c657-11eb-9ce2-4ffe87aa28c0.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.20

**Comment by Nomad-0** [comment]
> This issue has been potentially fixed in version 0.9.85.20

checked on 0.9.85.20, still not fixed
![image](https://user-images.githubusercontent.com/76395594/120955630-a054a380-c773-11eb-892f-e440daad8db4.png)

**Comment by Nomad-0** [comment]
Closing as the issue is fixed in 0.9.85.20. @Metroid-Prime can you please confirm as it's a _high priority_ issue?

**Comment by Metroid-Prime** [comment]
@Nomad-0   @adirh3   I'm tentatively re-opening this issue as I'm still experiencing the same thing on 0.9.85.20

From Changelog: - Fixed a bug that the minimal bar showed open when using Always hide results when opening #37

However, I have the setting turned on:
![image](https://user-images.githubusercontent.com/1836362/120959757-589c3080-c70f-11eb-9082-f7c8881caf8d.png)

![image](https://user-images.githubusercontent.com/1836362/120959807-6d78c400-c70f-11eb-80c5-23360ec1fb51.png)
![image](https://user-images.githubusercontent.com/1836362/120959813-710c4b00-c70f-11eb-9b2d-75468af4b866.png)

**Comment by Metroid-Prime** [comment]
Reopening issue as I cannot confirm fix in latest version.

**Comment by Nomad-0** [comment]
> Reopening issue as I cannot confirm fix in latest version.

Can you please check if your settings on settings>appearance>window style set to minimal?

**Comment by Metroid-Prime** [comment]
@Nomad-0  Yes, you nailed it, that's the reason, but choosing that feature should not cause this to happen.   When a user sets "Always hide results when opening", it should _always_ hide the results when opening.

@adirh3  This bug is resolved in minimal, but persistent when settings>appearance>window style is set to **informative**.
Informative mode should not show prior results as that wouldn't be in scope of the feature.

**Comment by Jaap-van-Hengstum** [comment]
If you ask me, "always hide results when opening" should be the default state for new installs, since it will be more familiar and (slightly) less confusing for new users. And then perhaps the option should be reversed, like "show results immediately when opening" or something.

**Comment by adirh3** [comment]
This_issue_has_been_potentially_fixed_in_version_

**Comment by Nomad-0** [comment]
Issue fix confirmed. Closing

**Comment by Chance92** [comment]
I am afraid the problem is back. The bottom pane keeps showing every time I invoke FS after a search, although the search results are hidden. I think the problem may be related to this one.
![bug](https://user-images.githubusercontent.com/85488695/122656954-1df6b700-d157-11eb-9f7b-d5ae4a175a1f.gif)

**Comment by Nomad-0** [comment]
@Metroid-Prime can you reproduce as per @Chance92-s comment? I am not being able to reproduce it

**Comment by Metroid-Prime** [comment]
> @Metroid-Prime can you reproduce as per @Chance92-s comment? I am not being able to reproduce it

No cannot replicate

**Comment by Chance92** [comment]
I reinstalled FS and I am still experiencing this bug. I hope I'm not the only one.

**Comment by Nomad-0** [comment]
could it be something on your settings? would you mind checking the issue with others on the discord server?

**Comment by Nomad-0** [comment]
Ok, I think @Chance92 is right, I'm suddenly facing a glitch like this issue. When I invoke FS, the result window appears with it and closes (very very fast). It's not constant though, I tried multiple times and faced the glitch. However, in some instances, the window opens like the picture below when I invoke FS. It's not constant but reproducible with several tries.  I informed Adir, and the issue's likely to be solved in the next update. so not reopening the issue.

https://discord.com/channels/740636963396124714/740636963836788818/856217576564588544

![image](https://user-images.githubusercontent.com/76395594/122682241-27952300-d21a-11eb-9d6d-7e4ab7a7fb19.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.85

**Comment by Nomad-0** [comment]
@Chance92 `can you please check and confirm?

**Comment by Chance92** [comment]
> @Chance92 `can you please check and confirm?

Yes, it seems to be fixed in 0.9.85.85
