### ISSUE TITLE
Previous entry shows in search bar

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#4]
When hitting search hotkey, the previous entry no longer shows based on a prior report:
![image](https://user-images.githubusercontent.com/1836362/120916126-91c79880-c65c-11eb-9637-fb3d345051e6.png)

_However_ , when triggering "Show" from right click menu of FS's systray icon, it still shows the previous search entry
![image](https://user-images.githubusercontent.com/1836362/120916135-a441d200-c65c-11eb-9403-d6917e6111fc.png)

**Comment by adirh3** [comment]
This_issue_has_been_potentially_fixed_in_version_

**Comment by Metroid-Prime** [comment]
> This issue has been potentially fixed in version 0.9.85.30

Unfortunately **not fixed in 0.9.85.35**  
![image](https://user-images.githubusercontent.com/1836362/121301515-2de7de80-c8ad-11eb-9c4c-268c2df722c1.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.40

**Comment by Metroid-Prime** [comment]
@adirh3  text is wiped on right click > show, but web searches, UI, and I imagine other search tags still show up from previous searches
![image](https://user-images.githubusercontent.com/1836362/121764968-a09ac900-cafc-11eb-9a49-e0ec17461b3d.png)

**Comment by adirh3** [comment]
> @adirh3 This is not completely fixed unfortunately.
> text is rightfully gone on right click > show, but web searches, UI, and I imagine other search tags still show up from previous searches
> ![image](https://user-images.githubusercontent.com/1836362/121764968-a09ac900-cafc-11eb-9a49-e0ec17461b3d.png)

It was by design, but I will change it, since I guess must users would want the tag to clear as well.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.50

**Comment by Metroid-Prime** [comment]
confirming fix & closing.

**Comment by Metroid-Prime** [comment]
I am reopening this issue as it's re-introduced from the right click "show" menu in v.80

**Comment by adirh3** [comment]
> I am reopening this issue as it's re-introduced from the right click "show" menu in v.80

This is intentional, I am going to change the name of the setting to reset search on hotkey and put it per hotkey setting.
