### ISSUE TITLE
FS opens with results of last tag launch. Results don't scroll into view at times.

### ISSUE THREAD

**Issue by erohtar** [adirh3/Fluent-Search#424]
**Describe the bug**
I have the home screen off and the max results set to default 15, and view set to full window.
1) When press hotkey to launch FS, the results list (which should be either empty or last few launched items, but instead it shows the same results it did with the last tag launch.
Here I pressed the hotkey associated with 'qmenu' tag:
![image](https://user-images.githubusercontent.com/5120628/149575095-acbaa699-314c-41ab-afe1-72d52f1d196c.png)

Then I press Esc, and press hotkey to launch default FS:
![image](https://user-images.githubusercontent.com/5120628/149575187-61d97b96-b9d6-48ae-9ef6-a810a614773e.png)

2) Now on that last window when I go down the list using arrow keys, once it goes past the last result in view (batch folder), it goes on the next one, but it doesn't scroll into view:
![image](https://user-images.githubusercontent.com/5120628/149575519-d2475214-243a-4cb8-907b-fb9e2f163b7f.png)

This happens only with the default launch with home screen off.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.98

**Comment by erohtar** [comment]
1. No this isn't fixed yet. If I do a tag search launch, it shows tag search results list, then I Esc out, do a normal launch and it still shows tag search results list, then I Esc out and do a normal launch and this time it shows the normal last launched result list.

2. The scrolling bug seems to be fixed now, thank you!

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.991

**Comment by Metroid-Prime** [comment]
@erohtar  let us know if it's resolved now

**Comment by erohtar** [comment]
Yes! looks like it's working as expected now - Thanks Adir!
