### ISSUE TITLE
when using IME,pressing backspace deletes the tag

### ISSUE THREAD

**Issue by u-Sir** [adirh3/Fluent-Search#428]
**Describe the bug**
when using IME,pressing backspace deletes the tag

**To Reproduce**
1. launch fs ,type any tag
2. type anything with IME
3. backspace 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11 Version: 21H2
 - Fluent Search Version 0.9.90.98

**Additional context**

https://user-images.githubusercontent.com/93647031/149612324-d0bdb1d5-7ea0-452b-9175-65d02a5f77c2.mp4

**Comment by adirh3** [comment]
Thanks @u-Sir, other than this, are there other issues with IME?

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.9997

**Comment by u-Sir** [comment]
> This issue has been potentially fixed in version 0.9.90.9997
the bug is not fixed. when the keyword is deleted, the tag gone too.
https://user-images.githubusercontent.com/93647031/152291376-fb1c2fac-2b02-488b-b74b-f85be7e46396.mp4

![图片](https://user-images.githubusercontent.com/93647031/152291615-7a292b34-41cf-4285-82d1-c44c1f2c498f.png)
![图片](https://user-images.githubusercontent.com/93647031/152291757-ecaace97-8355-4200-9990-cb93af85cd83.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.9998

**Comment by adirh3** [comment]
@u-Sir please let me know if this is fixed and there not other IME issues

**Comment by u-Sir** [comment]
> @u-Sir please let me know if this is fixed and there not other IME issues

thanks your job. it's fixed  in version 0.9.90.9998.
