### ISSUE TITLE
Settings & Plugin Setting windows always start collapsed.

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#441]
![image](https://user-images.githubusercontent.com/1836362/149641301-ba21a2b7-21e7-4d6e-abaa-378a37087226.png)

I can't figure out if this is intended behavior, but it's particularly ugh for the Search Applications.   I think FS should remember what the user had open last and default back to that.  

In current state on this beta, it opens closed every time.

![image](https://user-images.githubusercontent.com/1836362/149641277-40773929-ecd4-4e6a-8083-73ba451e1667.png)

**Comment by Nomad-0** [comment]
I second this, it's doesn't feel user-friendly open it everytime

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.995

**Comment by Metroid-Prime** [comment]
> This issue has been potentially fixed in version 0.9.90.995

I can confirm that it stays if I close the settings window, but the issue still happens after one exists FS.  Can we make it so that it remembers even when FS is shut down and restarted?   Do you agree this is what we want @Nomad-0  - even after shutting down Fluent Search and re-launching?

**Comment by Nomad-0** [comment]
> > This issue has been potentially fixed in version 0.9.90.995
> 
> I can confirm that it stays if I close the settings window, but the issue still happens after one exists FS. Can we make it so that it remembers even when FS is shut down and restarted? Do you agree this is what we want @Nomad-0 - even after shutting down Fluent Search and re-launching?

yes, I also think it should always be kept open unless I collapse it manually

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.9994

**Comment by Metroid-Prime** [comment]
@adirh3 
This is working only for plugins.  The search application is collapsing when FS is exited and re-launched
![image](https://user-images.githubusercontent.com/1836362/151687071-60ce5f5d-0c97-4913-84a2-d0116bbe4085.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.90.9995

**Comment by Metroid-Prime** [comment]
Can confirm, yay!
