### ISSUE TITLE
Multiple WebSearch Settings Panel Bugs / Improvements needed!

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#450]
@adirh3 

Now that the web search is scrolling quickly now via #435 (thank you!),  there are other issues with web panel that **badly** need your attention 

1. When clicking "+ / -" on the web search panel, the sorting of the entries gets reversed/scrambled.
2.  Please implement this if you agree:
![image](https://user-images.githubusercontent.com/1836362/149691499-dddc8b7e-5d10-4fd1-9028-8f35a13e8b4d.png)

3.  There is a _very specific_ bug where if the user adds a new web search entry or two and uses arrow keys to navigate, one cannot click DOWN ARROW after the 1rst "New" entry. See pic for illustration
![image](https://user-images.githubusercontent.com/1836362/149692524-2b7d2da5-ec0c-45bc-a550-bb4c57b16176.png)

4. **Please** allow multi-selecting using.  This is one of the most frustrating things about adding new entries in web search panel.
- Arrow Keys
- Mouse cicks
- page down/up keys 
- Control (select out of sequence) (e.g.1, 2, 4,5)
- Shift (select with a sequence e.g. 1 through 5)

5. Selecting rows are frustrating. 
![image](https://user-images.githubusercontent.com/1836362/149694724-6bcd2309-a751-4bb2-982f-d6eddb948c8c.png)

6. Please move these + & - buttons to top left or somewhere where the user will **ALWAYS** see them when scrolling! 
![image](https://user-images.githubusercontent.com/1836362/149613391-61c12645-4471-42cd-9f33-c43cf0c189bb.png)

![image](https://user-images.githubusercontent.com/1836362/149613426-40483784-79b4-4049-85c4-829cb117f7d1.png)

**Comment by Metroid-Prime** [comment]
Changing this to high priority due to  the fact that my web.json got  **completely wiped** while modifying some web search entries.  High confidence that this is an issue with the latest beta.

The file went from 2.4MB to 2kb (default

**Comment by Metroid-Prime** [comment]
@adirh3  please be aware I've added 1 more bug entries and 1 more improvement just now

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.12

**Comment by Metroid-Prime** [comment]
@adirh3 


**#2  #5  #7  #8  Not fixed.**   I would also like to add an entry number 11 please.
 
#1 - believe this is fixed
#2 - Still a problem
#3 - believe this is fixed
#4 - believe this is fixed
#5 - not fixed.  It's possible to select a row but wish it was a little easier to select the row without clicking into a typable field.
#6 - Fixed!! Yay!
#7 - definitely NOT  fixed
#8 -definitely NOT  fixed
#9 -  Fixed! Thank you!
10 - Fixed thank you! 


I would like to add #11 please. 


ENTRY 11:
![image](https://user-images.githubusercontent.com/1836362/153145759-84e615f2-817c-4301-b0f3-eff591ada9d4.png)

**Comment by Metroid-Prime** [comment]
Edited post per Adir's request with fixes.

**Comment by Metroid-Prime** [comment]
OMG @adirh3  so, so close!

The only one not fixed in the latest version  (.13) is this one: Websearch column sort gets lost when closing settings panel.
Every time I close FS it resets the entries with ### in the title which is sorted to the top.
[](https://user-images.githubusercontent.com/1836362/149701654-9f96c30c-0aa6-407b-be45-7af40d10b8f8.png)[BUG] (((still happening))))

**Comment by adirh3** [comment]
> OMG @adirh3 so, so close!
> 
> The only one not fixed in the latest version (.13) is this one: Websearch column sort gets lost when closing settings panel. Every time I close FS it resets the entries with ### in the title which is sorted to the top. ![image](https://user-images.githubusercontent.com/1836362/153360537-5a6f0409-b211-4702-ac9d-437d08050f00.png)

That's not a bug, I can change default to make it sort by Name, does that work as well?

**Comment by Metroid-Prime** [comment]
@adirh3 The best solution would be keep the sort based on user's prefs but for the purposes of saving you time and focus sort by name would be a viable solution too!   Not sure what it's being sorted as now.

**Comment by Metroid-Prime** [comment]
After a lengthy introspection period, I think sorting by name on default is the way to go.
I don't even know how it's sorted in current state (time of creation?)
