### ISSUE TITLE
Seeing a slight square corner line over the round corner

### ISSUE THREAD

**Issue by Nomad-0** [adirh3/Fluent-Search#62]
**Describe the bug**
Not sure if it's a bug or that's how it is, but I'm noticing a slight square corner over the round corner design on installed version of 0.9.85.20
![image](https://user-images.githubusercontent.com/76395594/120971138-1d8d1200-c78e-11eb-9d22-a5dbbf5652e0.png)
![image](https://user-images.githubusercontent.com/76395594/120971730-cb98bc00-c78e-11eb-82ef-72a1a5c03ab7.png)
![image](https://user-images.githubusercontent.com/76395594/120972210-54175c80-c78f-11eb-8a52-f33bc443e82e.png)

It's not much noticeable on the portable version though
![image](https://user-images.githubusercontent.com/76395594/120971208-309fe200-c78e-11eb-89b3-9298f0e4834d.png)

**To Reproduce**
Install the latest version.
open FS search bar.
Observe the corner carefully

**Expected behavior**
a completely round corner like the portable one given below
![image](https://user-images.githubusercontent.com/76395594/120971208-309fe200-c78e-11eb-89b3-9298f0e4834d.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: [21H1]
 - Fluent Search Version [0.9.85.2]

**Comment by Metroid-Prime** [comment]
Spoke to @Nomad-0  about this on the FS Discord channel. Cannot reproduce in portable version.

**Comment by adirh3** [comment]
Windows 10 does not support rounded corners, it's caused by the drop shadow effect in Windows, so you may see different results according to your system settings.
I can remove shadow but it's much needed for apps like FS that are displayed over other apps.

**Comment by Metroid-Prime** [comment]
I have drop shadow turned off which may explain why I am not seeing this.

**Comment by Nomad-0** [comment]
So, now the only workaround for this is turning of drop shadow? 
any reason it's not that much visible in portable version?

**Comment by Metroid-Prime** [comment]
correction: I turned off drop shadows and still see the white borders.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.50

**Comment by Nomad-0** [comment]
I'm still seeing this 
![image](https://user-images.githubusercontent.com/76395594/121834877-a3124400-ccf1-11eb-8982-c0babfc9514c.png)

**Comment by Nomad-0** [comment]
oh, sorry, found it in settings
