### ISSUE TITLE
Bug in FS Indexer in search by two Hebrew letters with tag

### ISSUE THREAD

**Issue by H5820121** [adirh3/Fluent-Search#629]
Sorry I'm reporting the bug only now, because until now I used the Everything indexer, and now that I saw that you wrote that the FS indexer is faster, I switched to it, and saw that there was a bug in FS Indexer in search by **two** Hebrew letters with **tag**.
In a search with the Everything indexer it finds well, as you can see in the screenshot
![image](https://user-images.githubusercontent.com/105562828/178550944-d9350855-fe0e-40e0-a24b-788629a81d99.png)

But when searching with an FS indexer he finds nothing and as you can see in the screenshot
![image](https://user-images.githubusercontent.com/105562828/178551402-e192bf2a-f4e3-4114-a28d-0491f5aaaf4c.png)

And only in a search by three letters he find well
![image](https://user-images.githubusercontent.com/105562828/178552226-b4990e38-05af-4fff-930b-1b5556c94c3d.png)

Thanks!

**Comment by H5820121** [comment]
![image](https://user-images.githubusercontent.com/105562828/178558375-f2dd5a94-fe9a-4d5e-9194-36eccd1bd44e.png)
![image](https://user-images.githubusercontent.com/105562828/178558558-5b225a6d-993e-41da-87ae-685fbe6f4231.png)

**Comment by adirh3** [comment]
Thanks @H5820121 :)

**Comment by H5820121** [comment]
Maybe it can help,
As the search is **without tag**, the FS Indexer finds well too

![image](https://user-images.githubusercontent.com/105562828/178794997-737a08ab-e253-42d7-bdc1-5eb0085bfb06.png)

And the strange thing is, even if the search is with a tag, if it's by **one** letter it does find it well

![image](https://user-images.githubusercontent.com/105562828/178795540-2007de18-2beb-4faa-836a-e3ec877052a6.png)

And the bug is only in search with a **tag** and by **two** letters

![image](https://user-images.githubusercontent.com/105562828/178795837-da417713-1e25-4255-aff3-2d9a705f7568.png)

**Comment by H5820121** [comment]
I ask out of curiosity, have you already been able to find the cause of this strange bug that is very interfering with the search with FS Indexer?

**Comment by adirh3** [comment]
> I ask out of curiosity, have you already been able to find the cause of this strange bug that is very interfering with the search with FS Indexer?

Yes I did, but a solution will not be available for a while unfortunately.
Will update here once it's fixed.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.33                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by H5820121** [comment]
Thanks, but still the bug is not fully fixed, in searching for **two** words by **two** letters with **tag**, and I will demonstrate it,
In a search with the Everything indexer it finds well, as you can see in the screenshot
 
![image](https://user-images.githubusercontent.com/105562828/184524596-86a0087f-5c5f-4ed2-83ef-9055b17718fa.png)

But when searching with an FS indexer he finds nothing and as you can see in the screenshot

![image](https://user-images.githubusercontent.com/105562828/184524549-7d7ce02a-9048-4ed1-a45a-2eb21896d7fc.png)

I am attaching the file with which I did the demo, I typed the name of the file inside the file as well.
[ףאבג דהוז.txt](https://github.com/adirh3/Fluent-Search/files/9332791/default.txt)

I greatly appreciate your great effort to bring the application to perfection, without any compromises!

**Comment by H5820121** [comment]
Thanks, but still the bug is not fully fixed, in searching for two words by two letters with tag, and I will demonstrate it,
In a search with the Everything indexer it finds well, as you can see in the screenshot

![image](https://user-images.githubusercontent.com/105562828/184525376-40d3c5cd-162e-4c96-b680-91be98b3f158.png)

But when searching with an FS indexer he finds nothing and as you can see in the screenshot

![image](https://user-images.githubusercontent.com/105562828/184525417-d595a11d-1f96-4316-b199-07ae60fc110f.png)


I am attaching the file with which I did the demo, I typed the name of the file inside the file as well.
[ףאבג דהוז.txt](https://github.com/adirh3/Fluent-Search/files/9332823/default.txt)

I greatly appreciate your great effort to bring the application to perfection, without any compromises!

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.36                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by H5820121** [comment]
Thanks! It seems that FS Indexer is now fully adapted to Hebrew as well, if I encounter a bug in the future I will report.
