### ISSUE TITLE
Active fileindexer service causes silent destiny 2 crash

### ISSUE THREAD

**Issue by zznty** [adirh3/Fluent-Search#657]
**Describe the bug**
Destiny 2 crashes if fluentsearch service is running in background

**To Reproduce**
1. install fluentsearch with file indexer enabled
2. install destiny 2 from steam
3. get past titlescreen of the game
4. see it will crash in about 2-3 minutes

**Expected behavior**
Fix this interraction with software 

**Desktop (please complete the following information):**
 - Windows 10 Version: 21H2 19044.1889
 - Fluent Search Version 0.9.91.0

**Additional context**
Getting same crash on win 11 too

**Comment by adirh3** [comment]
@zznty can you check if it happens if you add Destiny 2's executable file name to to `Ignore these processes for in app content search` in Settings -> Processes?

**Comment by zznty** [comment]
did not help, still the same crash
![image](https://user-images.githubusercontent.com/94796179/185471602-d4077dc5-cf57-4824-92d8-4547149f9bc5.png)

**Comment by adirh3** [comment]
@zznty Can you please enable `Gaming mode` in the system tray menu, and then open Destiny and let me know if it happens?

**Comment by zznty** [comment]
gaming mode seems has fixed the issue

**Comment by adirh3** [comment]
@zznty maybe the game is spawning multiple processes? if gaming mode fixes that than adding it to the ignore list or disabling `Search in app content` should fix the issue

**Comment by zznty** [comment]
disabled `Search in app content` and game still crashes, so only gaming mode helps.
game is starting through small laucher process which starts battleye service.
maybe there is something other, because destiny can crash due to game overlays (discord or msi afterburner)
