### ISSUE TITLE
FS taskbar icon is showing like an unknown program

### ISSUE THREAD

**Issue by Nomad-0** [adirh3/Fluent-Search#71]
**Describe the bug**
FS icon on taskbar is showing like this-
![image](https://user-images.githubusercontent.com/76395594/121028489-b42af480-c7c9-11eb-9904-fe0df29d2e00.png)

**To Reproduce**
1. open FS or FS settings
2. observe the taskbar icon

**Expected behavior**
FS logo will show on taskbar

**Desktop (please complete the following information):**
 - Windows 10 Version: [21H1]
 - Fluent Search Version [0.9.85.20]

**Comment by Metroid-Prime** [comment]
I've never seen this.  Was it introduced with the newest version?

**Comment by Nomad-0** [comment]
facing this since the last 2/3 versions

**Comment by kwanice** [comment]
i had today after doing something (??? dont know what)
=> to resolve, i closed FS and re open :)

**Comment by Nomad-0** [comment]
mine is also solved after the latest update. closing it.

**Comment by Nomad-0** [comment]
Reopening the issue as it's being inconsistent (sometimes shows the unknown icon, shows normal icon after restarting FS)

**Comment by kwanice** [comment]
I have also, i guess it's when we RESTART the computer.
If after restart, i close FS and reopen, everything  is ok :)

**Comment by Metroid-Prime** [comment]
@Nomad-0  I've been trying to reproduce this but I haven't been able to on 2 computers unfortunately.

**Comment by Nomad-0** [comment]
It shows the normal icon if I close and reopen FS. However, it get back to the unknown icon if I restart my pc.

**Comment by Metroid-Prime** [comment]
@Nomad-0 

I wonder if this might be a solution for you. 
Save this to notepad and name it as iconrefresh.BAT and double click on it. It will kill explorer, delete your icon cache and restart explorer.

After running this, restart your computer and see if it happens again?


```
@ ECHO off
Echo Run this if your Taskbar Icons look like blank rectangles
or your Explorer folders / Desktop does not auto-refresh.
Echo Tested for Win XP, Win7 and Server 2003/2010
Echo *****  Use at your own risk. *****
Echo Hit the  key to continue
Echo or the  and  keys to stop
REM  stop windows explorer desktop
taskkill /im explorer.exe /f"
REM  Change to your profile's application data folder
CD %USERPROFILE%\AppData\Local
REM change the permissions of the icon cache so we can see it
attrib -h IconCache.db
REM delete the corrupt icon cache
del IconCache.db
REM restart explorer which will rebuild the icon cache correctly
Echo If this did not work you may have bigger problems like a bad hard drive, corrupt registry or a virus.
Echo All Done!
Echo You may need to manually close this window now
call explorer.exe
```

**Comment by Nomad-0** [comment]
Tried the fix, @Metroid-Prime. It's still the same.

**Comment by Nomad-0** [comment]
@adirh3 @Metroid-Prime what if no icon appears at all in the taskbar? e.g. Listary, when I invoke it, no icon appears at the taskbar

**Comment by Metroid-Prime** [comment]
@Nomad-0  can you clarify what you meant in your post above? Perhaps with pics or video?

**Comment by Nomad-0** [comment]
LIke this, when you invoke, there's no taskbar icon
![image](https://user-images.githubusercontent.com/76395594/122151580-9fadc280-ce81-11eb-85a1-90e03a91d19a.png)

but when you invoke FS, there's this icon
![image](https://user-images.githubusercontent.com/76395594/122151734-de437d00-ce81-11eb-8de3-b99176756caa.png)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.75

**Comment by Nomad-0** [comment]
fixed on my end. @kwanice can you please confirm?

**Comment by kwanice** [comment]
yes for now seem to be ok, i just update and the icon seem ok, i will try to reboot now to check it :)

**Comment by kwanice** [comment]
ok for me its good ^^
after reboot the icon still appear :p 
good work ;)
