### ISSUE TITLE
After changing the software font, the software crashes and restarts

### ISSUE THREAD

**Issue by alelinshy** [adirh3/Fluent-Search#721]
**Describe the bug**
Changing the software font will cause the software to crash and restart,After that, the software cannot be used normally even if the restore function is used in the software..

**To Reproduce**
1. Go to 'Exterior'
2. Click on 'font'
3. Scroll down to 'Replace SourceHanSansCN'

**Screenshots**
![image](https://user-images.githubusercontent.com/44151430/204483338-8123ff82-c188-4065-96bc-873f74c849ff.png)
![image](https://user-images.githubusercontent.com/44151430/204483530-b61e581d-ddf8-42a7-b4b8-edf8b391d779.png)
![image](https://user-images.githubusercontent.com/44151430/204483578-d91ee430-5952-40a0-a079-61d9cdca015a.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: [22H2]
 - Fluent Search Version [ 0.9.91.9995]

**Comment by adirh3** [comment]
@alelinshy this should be fixed in the nightly builds
Would you mind checking it by changing the release feed in Settings -> System to Nightly?

**Comment by alelinshy** [comment]
> @alelinshy这应该在夜间构建中得到修复 您介意通过将“设置”->“系统”中的发布提要更改为“夜间”来检查它吗？

![image](https://user-images.githubusercontent.com/44151430/204491018-28c416dd-4dc1-4a94-87a4-28ad710c8144.png)

**Comment by alelinshy** [comment]
The beta version has been updated, but the problem still exists. Now every time I open the software switching option, the software will crash and restart

**Comment by alelinshy** [comment]
Uninstalling the software and then reinstalling it doesn't solve the problem

**Comment by adirh3** [comment]
@alelinshy thanks for checking.
Does it happen with all fonts or only the one you mentioned above? I see you use Chinese, have you tried Microsoft YaHei?

**Comment by alelinshy** [comment]
@adirh3 
After switching other fonts, the software will also crash and restart. The difference is that the font will be changed to "Segoe UI Variable Text Light" after restarting, but the software will still crash and restart.
![image](https://user-images.githubusercontent.com/44151430/204526271-68e63049-c3bf-416a-965c-0d2b003cf182.png)

**Comment by adirh3** [comment]
Thanks @alelinshy, I still can't reproduce this issue on my machine.
I will check it and update here once it's fixed.

**Comment by alelinshy** [comment]
I can't reproduce this problem in the virtual machine, I will try to find out the problem, but I found that even if I change the display font of the software in the settings, the text I type is not the font I choose

**Comment by alelinshy** [comment]
I did not test English, you can try it in Chinese, it should be reproducible
