### ISSUE TITLE
Settings / taskbar BUG

### ISSUE THREAD

**Issue by mragtronx8** [adirh3/Fluent-Search#733]
windows 10 22h2 - fs 0.9.92.65 
am unable to access my settings.
when i open settings, only titles appear on left side, and after that it freezes. and i cannot do anything in settings.
and when i close settings, fs search freezes.
also i can only access taskbar once, second use it freezes/doesn't respond

![image](https://user-images.githubusercontent.com/62798102/207403109-5e8eeca4-3bbb-4007-b94a-e3522c676e49.png)
#BUG

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.66                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by mragtronx8** [comment]
there is still a problem. I can only access setting thru the taskbar only one or two times.
after that taskbar is not responsive and fs freezes.

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.67                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe
