### ISSUE TITLE
File results showing "?" instead of icons 

### ISSUE THREAD

**Issue by Nomad-0** [adirh3/Fluent-Search#74]
**Describe the bug**
the thumbnail/icon for the first file result appears properly, but onwards it shows a '?' icon instead of the icons of the file types [not constant]

**To Reproduce**
1. Type a letter that invokes many results
2. Look at the icons
3. It may not be easy to reproduce as it's not constant

**Expected behavior**
Results will show the icon depending on the file type

**Screenshots**
most of the results below are pure file formats like pdf, mp4
![image](https://user-images.githubusercontent.com/76395594/121070856-092e3100-c7f1-11eb-8846-4e4fac8aeb9d.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: [21H1]
 - Fluent Search Version [0.9.85.2] (facing it from a lot earlier)

**Comment by Metroid-Prime** [comment]
I believe this is reproducible.

**Comment by Metroid-Prime** [comment]
@Nomad-0   @adirh3  can we make this a high priority ticket?  If you read the ticket on the surface it doesn't sound like, but this is really impactful on the user's workflow.  

For example, when I type in "medical" I expect a RAR file.  When the user has a lot of icons, I have to read through all of them vs just looking for the WinRAR archive icon.

**Comment by Nomad-0** [comment]
I agree, changing it

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.80

**Comment by Nomad-0** [comment]
I'm still facing it
![image](https://user-images.githubusercontent.com/76395594/122660397-1826c300-d1a3-11eb-9303-372acecc6728.png)

what about yours? @Metroid-Prime

**Comment by Metroid-Prime** [comment]
> I'm still facing it
> ![image](https://user-images.githubusercontent.com/76395594/122660397-1826c300-d1a3-11eb-9303-372acecc6728.png)
> 
> what about yours? @Metroid-Prime

Same :(

**Comment by adirh3** [comment]
@Nomad-0 the results with question mark are consistent? Or it changes randomly?

**Comment by Nomad-0** [comment]
> @Nomad-0 the results with question mark are consistent? Or it changes randomly?

It's random. Sometimes the results show question mark first and then change into the actual icon. Sometimes they don't

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.85

**Comment by Nomad-0** [comment]
Seems like it is fixed!! @Metroid-Prime can you please check and confirm?

**Comment by Metroid-Prime** [comment]
Ugggggggh, no not fixed on my end :(
![image](https://user-images.githubusercontent.com/1836362/122703027-8a2ff400-d205-11eb-9d38-7ce73e6fdbde.png)

![image](https://user-images.githubusercontent.com/1836362/122703036-8ef4a800-d205-11eb-974a-98d13d4bda38.png)

**Comment by Nomad-0** [comment]
I'm currently not facing it anymore. However, keeping it open for now

![image](https://user-images.githubusercontent.com/76395594/122704242-19282500-d275-11eb-9414-175a498a82be.png)

**Comment by Metroid-Prime** [comment]
I'm able to reproduce this on a second computer:
![image](https://user-images.githubusercontent.com/1836362/123155375-e7ea5900-d41c-11eb-8bd8-9dd489d22bcc.png)



However, it should be noted they both run LTSC 2019  (v1809  17763.1999) and have similar system configurations, but they are not clones.

**Comment by adirh3** [comment]
> I'm able to reproduce this on a second computer on a brand new portable installation of Fluent Search
> 
> ![image](https://user-images.githubusercontent.com/1836362/123155375-e7ea5900-d41c-11eb-8bd8-9dd489d22bcc.png)
> 
> It should be noted they both run LTSC 2019 (v1809 17763.1999) and have similar system configurations, but they are not clones.

Oh, it's 1809, there is a known issue in that version.
Sorry I forgot Nomad created the issue.

Will update here once it's solved.
