### ISSUE TITLE
Enable word wrapping in changelog window

### ISSUE THREAD

**Issue by Metroid-Prime** [adirh3/Fluent-Search#83]
![image](https://user-images.githubusercontent.com/1836362/121294553-72ba4800-c8a2-11eb-8a97-c4cd8b64c373.png)

**Comment by Nomad-0** [comment]
I think this is solved in recent updateds? @Metroid-Prime

**Comment by Metroid-Prime** [comment]
Still occurring 
![image](https://user-images.githubusercontent.com/1836362/122631742-a48d9480-d082-11eb-821b-15199ea7d79c.png)

**Comment by Metroid-Prime** [comment]
I'm reluctantly changing this to a low priority bug because Adir wants users to read changelog and this interfaces with that effort.

**Comment by Metroid-Prime** [comment]
Still happening in latest version .85

![image](https://user-images.githubusercontent.com/1836362/122875161-bff9d900-d2e8-11eb-839d-ad9393498518.png)

**Comment by Metroid-Prime** [comment]
@MakeshVineeth @Nomad-0   has anyone seen this issue recently? I don't recall seeing it in recent times but I'm not if @adirh3  fixed it and forgot to mention here?  Feel free to close if fixed.

**Comment by Nomad-0** [comment]
this still appears in some updates, and in some others, the letters are too small. However, can't recall how recent those updates were

**Comment by Metroid-Prime** [comment]
Thanks @Nomad-0  - will keep it open as it affects people's perceptions of FS and it's important for user to be able to read the changelog!

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.91.76                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by Metroid-Prime** [comment]
Thx Adir!
