### ISSUE TITLE
Vietnamese characters not supported when using 3rd party keyboard app

### ISSUE THREAD

**Issue by nhan000** [adirh3/Fluent-Search#839]
**Describe the bug**

When using 3rd party keyboard app for Vietnamese input such as [EVKey](https://evkeyvn.com/), [OpenKey](https://github.com/tuyenvm/OpenKey), [Unikey](https://www.unikey.org/), Fluent Search doesn't accept these inputs.

**To Reproduce**
1. Download https://github.com/tuyenvm/OpenKey/releases/tag/2.0.5 and run the program
2. Choose these 3 options:
![image](https://user-images.githubusercontent.com/85216095/236625494-79bd4be3-01f5-4560-a68f-4c521e60dbc6.png)

4. Open Fluent seach and type `a a` and see that the input disappear

https://user-images.githubusercontent.com/85216095/236625885-4761ed40-af0c-4548-bafb-35cc20f42528.mp4

**Expected behavior**
It's supposed to output this character: â when typing `a` twice.

**Desktop (please complete the following information):**
 - Window 11 Version 22H2
 - Fluent Search Version: 0.9.91.9994
 - Installation source: Microsoft Store

**Additional context**
Microsoft's built-in Vietnamese seems to work
<img src="https://user-images.githubusercontent.com/85216095/236626070-23b3abf8-83d9-46af-91e3-4dda96743111.png" width="600">

In this video, the first half I used Microsoft Vietnamese keyboard, the 2nd half I used a 3rd party keyboard.

https://user-images.githubusercontent.com/85216095/236627524-5d8dce2a-1611-45cd-8eb5-167857d01872.mp4

Let me know if anything isn't clear. Thank you!

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.11                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by adirh3** [comment]
@nhan000 can you check if it still happens in latest beta?

**Comment by nhan000** [comment]
Hi @adirh3, sorry for the late reply. I wanted to wait until FS comes out of beta. Anyway, I have uninstalled FS and installed the latest version (1.0.0.22) and the issue is still there. It actually got worse: Now I can't even type Vietnamese using the Microsoft Vietnamese Keyboard.

**Comment by adirh3** [comment]
@nhan000 did you have a chance to check in `1.0.0.33`?
