### ISSUE TITLE
Tab search doesn't work in most apps

### ISSUE THREAD

**Issue by Gortus** [adirh3/Fluent-Search#850]
**Describe the bug**
Searching for a specific process tab via the Tab keyword or in-app search works in some apps (VSCode, Edge, Opera) but not others (Firefox, Vivaldi, MediaMonkey).

**To Reproduce**
1. Install and run Firefox web browser
2. Go to a web site, e.g. https://github.com
3. Create a second tab (Ctrl-T)
4. Go to a second web site, e.g. https://www.reddit.com
5. Activate Fluent Search (Alt-Space for me)
6. Type "tab"
7. Hit tab key to activate tab search
8. Start typing the name of the site in #2, e.g. "git"
9. Search result is "None Nothing to show"

**Expected behavior**
A search result should show the Firefox process, with the title of the tab in question.

**Screenshots**
Can be supplied on request

**Desktop (please complete the following information):**
 - Windows 10 Home 22H2
 - Fluent Search Version: 0.9.92.99 
 - Installation source: Installer (also downloaded portable versions of the last two stable releases, behaves the same)

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 1.0.0.26                                          . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by Gortus** [comment]
I still get the reproduce behavior instead of the expected behavior. Version 1.0.0.29.

**Comment by albertohernandezalcaina** [comment]
I have tested and it works for me with the current nightly version @Gortus 
have you tried:
settings (from within fluent search) -> apps -> windows(s)
activate the "Search in window content"

![fluent search](https://github.com/adirh3/Fluent-Search/assets/22517436/74f84fef-0768-40ee-9126-66b57406fb20)

**Comment by Gortus** [comment]
That setting is on. As of version 1.0.0.43 it still doesn't work for me in Firefox and still works properly in Edge. I haven't re-tested the other four example apps I gave.
